// Mocks generated by Mockito 5.4.4 from annotations
// in tap_and_learn/test/features/arithmetic/presentation/bloc/exercise_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:bloc/bloc.dart' as _i11;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:tap_and_learn/core/error/faiures.dart' as _i9;
import 'package:tap_and_learn/features/arithmetic/domain/entities/exercise.dart'
    as _i10;
import 'package:tap_and_learn/features/arithmetic/domain/logic/arithmetic_strategy.dart'
    as _i12;
import 'package:tap_and_learn/features/arithmetic/domain/repositories/arithmetic_repository.dart'
    as _i2;
import 'package:tap_and_learn/features/arithmetic/domain/usecases/generate_exercise.dart'
    as _i7;
import 'package:tap_and_learn/features/arithmetic/domain/usecases/get_selected_operands1.dart'
    as _i4;
import 'package:tap_and_learn/features/arithmetic/domain/usecases/save_selected_operands1.dart'
    as _i5;
import 'package:tap_and_learn/features/arithmetic/presentation/widgets/operand_selector/cubit/operand_config_cubit.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArithmeticRepository_0 extends _i1.SmartFake
    implements _i2.ArithmeticRepository {
  _FakeArithmeticRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetSelectedOperands1_2 extends _i1.SmartFake
    implements _i4.GetSelectedOperands1 {
  _FakeGetSelectedOperands1_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveSelectedOperands1_3 extends _i1.SmartFake
    implements _i5.SaveSelectedOperands1 {
  _FakeSaveSelectedOperands1_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOperandConfigState_4 extends _i1.SmartFake
    implements _i6.OperandConfigState {
  _FakeOperandConfigState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GenerateExercise].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerateExercise extends _i1.Mock implements _i7.GenerateExercise {
  MockGenerateExercise() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ArithmeticRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeArithmeticRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ArithmeticRepository);

  @override
  _i8.Future<_i3.Either<_i9.Failure, _i10.Exercise>> call(_i7.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i8.Future<_i3.Either<_i9.Failure, _i10.Exercise>>.value(
            _FakeEither_1<_i9.Failure, _i10.Exercise>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i8.Future<_i3.Either<_i9.Failure, _i10.Exercise>>);
}

/// A class which mocks [OperandConfigCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockOperandConfigCubit extends _i1.Mock
    implements _i6.OperandConfigCubit {
  MockOperandConfigCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GetSelectedOperands1 get getSelectedOperands1 => (super.noSuchMethod(
        Invocation.getter(#getSelectedOperands1),
        returnValue: _FakeGetSelectedOperands1_2(
          this,
          Invocation.getter(#getSelectedOperands1),
        ),
      ) as _i4.GetSelectedOperands1);

  @override
  _i5.SaveSelectedOperands1 get saveSelectedOperands1 => (super.noSuchMethod(
        Invocation.getter(#saveSelectedOperands1),
        returnValue: _FakeSaveSelectedOperands1_3(
          this,
          Invocation.getter(#saveSelectedOperands1),
        ),
      ) as _i5.SaveSelectedOperands1);

  @override
  _i6.OperandConfigState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeOperandConfigState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.OperandConfigState);

  @override
  _i8.Stream<_i6.OperandConfigState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i8.Stream<_i6.OperandConfigState>.empty(),
      ) as _i8.Stream<_i6.OperandConfigState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> toggleOperand(int? operand) => (super.noSuchMethod(
        Invocation.method(
          #toggleOperand,
          [operand],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateOperands1(List<int>? newOperands) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOperands1,
          [newOperands],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void emit(_i6.OperandConfigState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i11.Change<_i6.OperandConfigState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [ArithmeticStrategy].
///
/// See the documentation for Mockito's code generation for more information.
class MockArithmeticStrategy extends _i1.Mock
    implements _i12.ArithmeticStrategy {
  MockArithmeticStrategy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get symbol => (super.noSuchMethod(
        Invocation.getter(#symbol),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#symbol),
        ),
      ) as String);

  @override
  int calculate(
    int? operand1,
    int? operand2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculate,
          [
            operand1,
            operand2,
          ],
        ),
        returnValue: 0,
      ) as int);
}
