// Mocks generated by Mockito 5.4.4 from annotations
// in multiplication_trainer/test/features/arithmetic/presentation/bloc/multiplication_exercise_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:bloc/bloc.dart' as _i9;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tap_and_learn/core/error/faiures.dart' as _i7;
import 'package:tap_and_learn/features/arithmetic/domain/entities/multiplication_exercise.dart'
    as _i8;
import 'package:tap_and_learn/features/arithmetic/domain/repositories/arithmetic_repository.dart'
    as _i2;
import 'package:tap_and_learn/features/arithmetic/domain/usecases/generate_multiplication_exercise.dart'
    as _i5;
import 'package:tap_and_learn/features/arithmetic/presentation/widgets/multiplicand_selector/cubit/multiplicand_config_cubit.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArithmeticRepository_0 extends _i1.SmartFake
    implements _i2.ArithmeticRepository {
  _FakeArithmeticRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiplicandConfigState_2 extends _i1.SmartFake
    implements _i4.MultiplicandConfigState {
  _FakeMultiplicandConfigState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GenerateMultiplicationExercise].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerateMultiplicationExercise extends _i1.Mock
    implements _i5.GenerateMultiplicationExercise {
  MockGenerateMultiplicationExercise() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ArithmeticRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeArithmeticRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ArithmeticRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.MultiplicationExercise>> call(
          _i5.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6
            .Future<_i3.Either<_i7.Failure, _i8.MultiplicationExercise>>.value(
            _FakeEither_1<_i7.Failure, _i8.MultiplicationExercise>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, _i8.MultiplicationExercise>>);
}

/// A class which mocks [MultiplicandConfigCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultiplicandConfigCubit extends _i1.Mock
    implements _i4.MultiplicandConfigCubit {
  MockMultiplicandConfigCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MultiplicandConfigState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeMultiplicandConfigState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.MultiplicandConfigState);

  @override
  _i6.Stream<_i4.MultiplicandConfigState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i6.Stream<_i4.MultiplicandConfigState>.empty(),
      ) as _i6.Stream<_i4.MultiplicandConfigState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void toggleMultiplicand(int? multiplicand) => super.noSuchMethod(
        Invocation.method(
          #toggleMultiplicand,
          [multiplicand],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateMultiplicands(List<int>? newMultiplicands) => super.noSuchMethod(
        Invocation.method(
          #updateMultiplicands,
          [newMultiplicands],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.MultiplicandConfigState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i9.Change<_i4.MultiplicandConfigState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
