// Mocks generated by Mockito 5.4.4 from annotations
// in tap_and_learn/test/features/arithmetic/data/repositories/arithmetic_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:math' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tap_and_learn/features/arithmetic/data/datasources/arithmetic_local_data_source.dart'
    as _i4;
import 'package:tap_and_learn/features/arithmetic/data/models/exercise_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRandom_0 extends _i1.SmartFake implements _i2.Random {
  _FakeRandom_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExerciseModel_1 extends _i1.SmartFake implements _i3.ExerciseModel {
  _FakeExerciseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ArithmeticLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockArithmeticLocalDataSource extends _i1.Mock
    implements _i4.ArithmeticLocalDataSource {
  MockArithmeticLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Random get random => (super.noSuchMethod(
        Invocation.getter(#random),
        returnValue: _FakeRandom_0(
          this,
          Invocation.getter(#random),
        ),
      ) as _i2.Random);

  @override
  _i5.Future<_i3.ExerciseModel> generateExercise(List<int>? operands1) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateExercise,
          [operands1],
        ),
        returnValue: _i5.Future<_i3.ExerciseModel>.value(_FakeExerciseModel_1(
          this,
          Invocation.method(
            #generateExercise,
            [operands1],
          ),
        )),
      ) as _i5.Future<_i3.ExerciseModel>);

  @override
  _i5.Future<List<int>> getSelectedOperands1() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedOperands1,
          [],
        ),
        returnValue: _i5.Future<List<int>>.value(<int>[]),
      ) as _i5.Future<List<int>>);

  @override
  _i5.Future<void> saveSelectedOperands1(List<int>? operands1) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSelectedOperands1,
          [operands1],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
