// Mocks generated by Mockito 5.4.4 from annotations
// in tap_and_learn/test/features/arithmetic/domain/usecases/get_selected_operands1_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tap_and_learn/core/error/faiures.dart' as _i5;
import 'package:tap_and_learn/features/arithmetic/domain/entities/exercise.dart'
    as _i6;
import 'package:tap_and_learn/features/arithmetic/domain/repositories/arithmetic_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ArithmeticRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArithmeticRepository extends _i1.Mock
    implements _i3.ArithmeticRepository {
  MockArithmeticRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Exercise>> generateExercise(
          List<int>? operands1) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateExercise,
          [operands1],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Exercise>>.value(
            _FakeEither_0<_i5.Failure, _i6.Exercise>(
          this,
          Invocation.method(
            #generateExercise,
            [operands1],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Exercise>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<int>>> getSelectedOperands1() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSelectedOperands1,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<int>>>.value(
            _FakeEither_0<_i5.Failure, List<int>>(
          this,
          Invocation.method(
            #getSelectedOperands1,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<int>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveSelectedOperands1(
          List<int>? operands1) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSelectedOperands1,
          [operands1],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveSelectedOperands1,
            [operands1],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
